# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-27 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stage_name',
            field=models.CharField(max_length=30),
        ),
    ]
