# Generated by Django 2.2.6 on 2019-10-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='county',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='major_skill',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='minor_skill',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='urban_centre',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='urban',
            name='county',
        ),
        migrations.DeleteModel(
            name='Counties',
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Minor',
        ),
        migrations.DeleteModel(
            name='Urban',
        ),
    ]
