# Generated by Django 2.2.6 on 2019-10-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Counties'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='major_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_skill', to='accounts.Skills'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='minor_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_skill', to='accounts.Skills'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='urban_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Urban'),
        ),
    ]
