# Generated by Django 2.2.6 on 2019-10-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='county',
        ),
    ]
