# Generated by Django 2.2.6 on 2019-10-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191003_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.AddField(
            model_name='creator',
            name='image',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
