# Generated by Django 2.2.6 on 2019-10-09 11:43

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191009_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(null=True, upload_to='profile/')),
                ('stage_name', models.CharField(max_length=100, null=True)),
                ('Phone', models.CharField(max_length=10)),
                ('bio', models.TextField(max_length=500)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Counties')),
            ],
            options={
                'verbose_name': 'Creator',
                'verbose_name_plural': 'Creators',
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Urban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urban_centre', models.CharField(max_length=100, null=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('invite_reason', models.CharField(max_length=64)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Creator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='accounts.Membership', to='accounts.Creator'),
        ),
        migrations.AddField(
            model_name='creator',
            name='major_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Major'),
        ),
        migrations.AddField(
            model_name='creator',
            name='minor_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Minor'),
        ),
        migrations.AddField(
            model_name='creator',
            name='urban_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Urban'),
        ),
    ]
