# Generated by Django 2.2.6 on 2019-10-03 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0002_auto_20191003_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='profile/')),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Creator')),
                ('major_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Creator')),
                ('minor_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Creator')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Creator')),
                ('stage_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Creator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-profile'],
            },
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
