# Generated by Django 2.2.6 on 2019-10-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191015_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
