# Generated by Django 2.2.6 on 2019-10-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191016_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='county',
        ),
    ]
