# Generated by Django 2.2.6 on 2019-10-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191003_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
