# Generated by Django 2.2.6 on 2019-10-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191022_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_creator',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_sponsor',
        ),
    ]
