# Generated by Django 2.2.6 on 2019-10-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191009_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='Phone',
            new_name='phone',
        ),
    ]
