# Generated by Django 2.2.6 on 2019-10-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191010_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='agree_to_license',
            field=models.BooleanField(default=False),
        ),
    ]
