# Generated by Django 2.2.6 on 2019-10-24 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191024_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='group',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_modifiedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
